services:

  mongo:
    image: mongo:latest
    ports:
      - 9000:27017

  api:
    build: .
    image: petworld-api
    depends_on:
      - mongo
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    command: npm run dev